version: '3'

services: 
  ng-postgres: 
    container_name: ng-postgres
    # image: postgres:latest
    build:
      context: .
      dockerfile: Dockerfile.database
    environment: 
      POSTGRES_USER: cashier
      POSTGRES_PASSWORD: cashier
      POSTGRES_PORT: 5432
      POSTGRES_DB: ngcash
    ports: 
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - api-net

  ngcash:
    container_name: ngcash
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - API_URL=${API_URL}
      - PORT=${PORT}
      - LOCAL_URL=${LOCAL_URL}
      - SECRET_KEY=${SECRET_KEY}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGHOST=${PGHOST}
      - PGPORT=${PGPORT}
      - PGDATABASE=${PGDATABASE}
    command: npm run start
    ports: 
        - "3000:3000"
    depends_on:
      - ng-postgres
    links: 
        - ng-postgres
    networks:
      - api-net
networks:
  api-net:



