version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6
workflows:
  version: 2
    build_test_deploy:
      jobs:
        - heroku/deploy-via-git
        - test:
            requires:
              - build
        - deploy:
            requires:
              - test
            filters:
              branches:
                only: master