# version: 2.1
# orbs:
#   heroku: circleci/heroku@1.2.6
# workflows:
#   heroku_deploy:
#     jobs:
#       - heroku/deploy-via-git


version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6
jobs:
  heroku_deploy:
    - heroku/deploy-via-git
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:16.00.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          command: npm test